version: '3.8'

services:
  monogodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:8080
  app:
    depends_on:
      - monogodb
    image: ghcr.io/electrolyte-orb/back4app-image-geister:latest
    restart: unless-stopped
    ports:
      - 3000:3000