name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: mv ./docker/nextjs.dockerfile ./Dockerfile |
          docker build . --file Dockerfile --tag ghcr.io/electrolyte-orb/back4app-image-geister:latest
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Publish to Github Packages
        run: docker push ghcr.io/${{ github.repository_owner }}/back4app-image-geister:latest
