name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  build-nextjs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Meta Data
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/electrolyte-orb/back4app-image-geister
          tags: |
            type=raw,value=latest
            type=raw,value={{ date 'YYYY-MM-DD--h:mm:ssa' tz='Asia/Kolkata'}}
      - name: Copy the dockerfile to .
        run: cp ./docker/nextjs.dockerfile ./Dockerfile
      
      - name: Build and Publish to Github Packages
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  build-mongo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Meta Data
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/electrolyte-orb/microg-db
          tags: |
            type=raw,value=latest
            type=raw,value={{ date 'YYYY-MM-DD--h:mm:ssa' tz='Asia/Kolkata'}}
      - name: Copy the dockerfile to .
        run: cp ./docker/mongo.dockerfile ./Dockerfile
      
      - name: Build and Publish to Github Packages
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}